/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;

public class fatsCase1 extends javax.swing.JFrame {

   private String loggedUsername;

    public fatsCase1(String username) {
        this.loggedUsername = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        c500 = new javax.swing.JCheckBox();
        c1000 = new javax.swing.JCheckBox();
        c1500 = new javax.swing.JCheckBox();
        c2000 = new javax.swing.JCheckBox();
        c3000 = new javax.swing.JCheckBox();
        c5000 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 233, 246));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("                                                                          FAST CASE");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jButton3.setBackground(new java.awt.Color(206, 233, 246));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Documents\\bb.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("HOW MUCH MONEY YOU WANT CASE");

        c500.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c500.setText("500.00");

        c1000.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c1000.setText("1000.00");

        c1500.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c1500.setText("1500.00");

        c2000.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c2000.setText("2000.00");

        c3000.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c3000.setText("3000.00");

        c5000.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        c5000.setText("5000.00");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c1500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c2000))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c1000))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(c3000)
                        .addGap(278, 278, 278)
                        .addComponent(c5000)))
                .addGap(241, 241, 241))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c500)
                    .addComponent(c1000))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1500)
                    .addComponent(c2000))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c3000)
                    .addComponent(c5000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Afterlogin1 afterLoginWindow = new Afterlogin1(loggedUsername);
        afterLoginWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double balance = getBalanceFormDb(loggedUsername);
        double totalWith = 0;
        if (c500.isSelected()) {
            totalWith += 500;
        }
        if (c1000.isSelected()) {
            totalWith += 1000;
        }
        if (c2000.isSelected()) {
            totalWith += 2000;
        }
        if (c3000.isSelected()) {
            totalWith += 3000;
        }
        if (c5000.isSelected()) {
            totalWith += 5000;
        }
        if (c1500.isSelected()) {
            totalWith += 1500;
        }

        if (totalWith > 0) {
            if (totalWith <= balance) {
                double newBalance = balance - totalWith; // New balance calculation
                updateBalanceInDB(loggedUsername, newBalance); // Database update
                JOptionPane.showMessageDialog(this, "₹" + totalWith + " withdrawn!\nNew Balance: ₹" + newBalance);
                try {
                    Thread.sleep(1000);  // 1-second delay
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                //                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Insufficient balance!\nCurrent Balance: ₹" + balance);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an amount to withdraw!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
      private double getBalanceFormDb(String username) {
        double balance = 0;
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/BMSG", "root", "root");
            String query = "SELECT balance FROM users WHERE username=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, loggedUsername);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                balance = rs.getDouble("balance");
            } else {
                JOptionPane.showMessageDialog(this, "User not found!");
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
        return balance;
    }

      
         public void updateBalanceInDB(String username, double newBalance) {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/BMSG", "root", "root");
            String query = "update users set balance=? where username= ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setDouble(1, newBalance);
            pst.setString(2, loggedUsername);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating balance" + e.getMessage());
        }
    }
         
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       String username=null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fatsCase1(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1000;
    private javax.swing.JCheckBox c1500;
    private javax.swing.JCheckBox c2000;
    private javax.swing.JCheckBox c3000;
    private javax.swing.JCheckBox c500;
    private javax.swing.JCheckBox c5000;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
