/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormThree1 extends javax.swing.JFrame {

     private String loggedUsername;
    public FormThree1(String username) {
        this.loggedUsername=username;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        savingRadioButton = new javax.swing.JRadioButton();
        fixedRadioButton = new javax.swing.JRadioButton();
        currentRadioButton = new javax.swing.JRadioButton();
        recurringRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        atmCardCheckBox = new javax.swing.JCheckBox();
        internetBankingCheckBox = new javax.swing.JCheckBox();
        emailAlertCheckBox = new javax.swing.JCheckBox();
        mobileBankingCheckBox = new javax.swing.JCheckBox();
        chequeBookCheckBox = new javax.swing.JCheckBox();
        eStatementCheckBox = new javax.swing.JCheckBox();
        declarationCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(209, 233, 246));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("                   Page 3 : Account Details");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        label.setText("Account Type :");

        savingRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        savingRadioButton.setText("Saving Account");
        savingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingRadioButtonActionPerformed(evt);
            }
        });

        fixedRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fixedRadioButton.setText("Fixed Deposite Account");

        currentRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        currentRadioButton.setText("Current Account");
        currentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentRadioButtonActionPerformed(evt);
            }
        });

        recurringRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        recurringRadioButton.setText("Recurring Deposite Account");
        recurringRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recurringRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Service Required :");

        atmCardCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atmCardCheckBox.setText("ATM  CARD");
        atmCardCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atmCardCheckBoxActionPerformed(evt);
            }
        });

        internetBankingCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        internetBankingCheckBox.setText("Internet Banking");
        internetBankingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetBankingCheckBoxActionPerformed(evt);
            }
        });

        emailAlertCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailAlertCheckBox.setText("EMAIL Alert");
        emailAlertCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAlertCheckBoxActionPerformed(evt);
            }
        });

        mobileBankingCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mobileBankingCheckBox.setText("Mobile Banking");
        mobileBankingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileBankingCheckBoxActionPerformed(evt);
            }
        });

        chequeBookCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chequeBookCheckBox.setText("Cheque Book");
        chequeBookCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeBookCheckBoxActionPerformed(evt);
            }
        });

        eStatementCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eStatementCheckBox.setText("E-Statement");
        eStatementCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStatementCheckBoxActionPerformed(evt);
            }
        });

        declarationCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        declarationCheckBox.setText("I hereby declares that the abov entered details correct to the best of my knowlwdge");
        declarationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declarationCheckBoxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cencel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(144, 144, 144))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(savingRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 26, Short.MAX_VALUE))
                                            .addComponent(currentRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(atmCardCheckBox)
                                        .addComponent(mobileBankingCheckBox)
                                        .addComponent(chequeBookCheckBox)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(internetBankingCheckBox)
                                    .addComponent(fixedRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recurringRadioButton)
                                    .addComponent(emailAlertCheckBox)
                                    .addComponent(eStatementCheckBox)))
                            .addComponent(declarationCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(label)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingRadioButton)
                    .addComponent(fixedRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentRadioButton)
                    .addComponent(recurringRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atmCardCheckBox)
                    .addComponent(internetBankingCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAlertCheckBox)
                    .addComponent(mobileBankingCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chequeBookCheckBox)
                    .addComponent(eStatementCheckBox))
                .addGap(77, 77, 77)
                .addComponent(declarationCheckBox)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingRadioButtonActionPerformed

    }//GEN-LAST:event_savingRadioButtonActionPerformed

    private void currentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentRadioButtonActionPerformed

    private void recurringRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recurringRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recurringRadioButtonActionPerformed

    private void atmCardCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atmCardCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atmCardCheckBoxActionPerformed

    private void internetBankingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetBankingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internetBankingCheckBoxActionPerformed

    private void emailAlertCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAlertCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAlertCheckBoxActionPerformed

    private void mobileBankingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileBankingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileBankingCheckBoxActionPerformed

    private void chequeBookCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeBookCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chequeBookCheckBoxActionPerformed

    private void eStatementCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStatementCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eStatementCheckBoxActionPerformed

    private void declarationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declarationCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_declarationCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!declarationCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this,
                "Please check the declaration to proceed.",
                "Declaration Required",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String account_type = "";
        if(savingRadioButton.isSelected()) {
            account_type = "Saving";
        } else if(fixedRadioButton.isSelected()) {
            account_type = "Fixed Deposit";
        } else if(currentRadioButton.isSelected()) {
            account_type = "Current";
        } else if(recurringRadioButton.isSelected()) {
            account_type = "Recurring Deposit";
        }

        StringBuilder service_required = new StringBuilder();
        if(atmCardCheckBox.isSelected()) {
            service_required.append("ATM CARD, ");
        }
        if(internetBankingCheckBox.isSelected()) {
            service_required.append("Internet Banking, ");
        }
        if(mobileBankingCheckBox.isSelected()) {
            service_required.append("Mobile Banking, ");
        }
        if(emailAlertCheckBox.isSelected()) {
            service_required.append("EMAIL Alert, ");
        }
        if(chequeBookCheckBox.isSelected()) {
            service_required.append("Cheque Book, ");
        }
        if(eStatementCheckBox.isSelected()) {
            service_required.append("E-Statement, ");
        }

        Random rd=new Random();
        String account_number=String.format("%010d",rd.nextInt(1000000000));

        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/BMSG","root","root");
            String query ="update users set account_type=?,service_required=?,account_number=? where username = ?";
            PreparedStatement  pst =con.prepareStatement(query);
            pst.setString(1, account_type);
            pst.setString(2, service_required.toString());
            pst.setString(3, account_number);
            pst.setString(4, loggedUsername);

            int result = pst.executeUpdate();
            if(result > 0) {
                JOptionPane.showMessageDialog(this, "Account successfully created! Account Number: " + account_number);

                new LoginOne1(loggedUsername).setVisible(true);
                this.dispose();
            }

        }   catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error :"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();

        FormThree1 ft=new FormThree1(loggedUsername);
        ft.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       String username=null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThree1(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox atmCardCheckBox;
    private javax.swing.JCheckBox chequeBookCheckBox;
    private javax.swing.JRadioButton currentRadioButton;
    private javax.swing.JCheckBox declarationCheckBox;
    private javax.swing.JCheckBox eStatementCheckBox;
    private javax.swing.JCheckBox emailAlertCheckBox;
    private javax.swing.JRadioButton fixedRadioButton;
    private javax.swing.JCheckBox internetBankingCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JCheckBox mobileBankingCheckBox;
    private javax.swing.JRadioButton recurringRadioButton;
    private javax.swing.JRadioButton savingRadioButton;
    // End of variables declaration//GEN-END:variables
}
